<?php

namespace app\index\controller;

use think\Controller;
use think\Db;
use app\index\model\Special;
use app\index\model\Brand;
use app\index\model\Lantern;

class Lanterns extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('active_type', "lantern");

        if(empty(session("user_id"))){
            $url="/index";
            Header("Location: $url");
            exit;
        }
    }

    public function lantern_list()
    {

        $lanternModel = new lantern;
        $list = $lanternModel->paginate(20, false, [
            'var_page' => 'page\Page',
            'list_rows' => 20,
        ]);
        $page = $list->render();
        $this->assign('list', $list);
        $this->assign('page', $page);
        return $this->fetch('lantern/lantern_index.html');

    }


    /**
     * @Description:添加加载
     * @author:lizx
     * @date:2017年12月2日
     */
    public function lantern_add()
    {

        $brandModel = new Brand();
        $brandList = $brandModel->select();
        $this->assign('brandList', $brandList);

        $specialModel = new Special();
        $specialList = $specialModel->select();
        $this->assign('specialList', $specialList);

        return $this->fetch('lantern/lantern_add.html');
    }


    /**
     * @Description:添加加载
     * @author:lizx
     * @date:2017年12月2日
     */
    public function lantern_save()
    {
        $brand_id = $this->request->param("brand_id");
        $special_id = $this->request->param("special_id");
        $year = $this->request->param("year");
        $lamp_status = $this->request->param("lamp_status");
        $box_status = $this->request->param("box_status");
        $num = $this->request->param("num");


        $data=array(
            "brand_id" => $brand_id,
            "special_id" => $special_id,
            "year" => $year,
            "lamp_status" => $lamp_status,
            "box_status" => $box_status,
            "num" => $num,
            "create_time" => date("Y-m-d H:i:s"),
        );
        $bool = Db::table('lantern')->insert($data);
        if ($bool) {
            echo json_encode(array("type" => true,"msg"=>"添加成功"));
        } else {
            echo json_encode(array("type" => false,"msg"=>"失败成功"));
        }

    }

    /**
     * @Description:添加加载
     * @author:lizx
     * @date:2017年12月2日
     */
    public function lantern_load()
    {
        $lantern_id = $_REQUEST["lantern_id"];
        $lanternData = Db::table('lantern')->where(array("lantern_id" => $lantern_id))->find();
        $this->assign('lanternData', $lanternData);

        $brandModel = new Brand();
        $brandList = $brandModel->select();
        $this->assign('brandList', $brandList);


        $specialModel = new Special();
        $specialList = $specialModel->select();
        $this->assign('specialList', $specialList);



        return $this->fetch('lantern/lantern_load.html');

    }


    /**
     * @Description:添加加载
     * @author:lizx
     * @date:2017年12月2日
     */
    public function lantern_update()
    {
        $lantern_id = $_REQUEST["lantern_id"];
        $lantern_name = $_REQUEST["lantern_name"];
        $brand_id = $_REQUEST["brand_id"];
        $bool = Db::table('lantern')->where(array("lantern_id" => $lantern_id))->update(array("brand_id" => $brand_id, "lantern_name" => $lantern_name));
        if ($bool) {
            echo json_encode(array("type" => true,"msg"=>"修改成功"));
        } else {
            echo json_encode(array("type" => false,"msg"=>"修改成功"));
        }

    }



    /**
     * @Description:删除
     * @author:lizx
     * @date:2017年12月2日
     */
    public function lantern_delete()
    {
        $lantern_id = $_REQUEST["lantern_id"];
        $bool = Db::table('lantern')->where(array("lantern_id" => $lantern_id))->delete();
        if($bool){
            echo json_encode(array("type" => true,"msg"=>"删除成功"));
        }else{
            echo json_encode(array("type" => false,"msg"=>"删除失败"));
        }

    }

}
